// <auto-generated />
using System;
using DataLayer.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataLayer.Migrations
{
    [DbContext(typeof(EShopDbContext))]
    partial class EShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataLayer.Entities.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Blog");
                });

            modelBuilder.Entity("DataLayer.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Available")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("BookImage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("https://www.vinabook.com/images/thumbnails/product/240x/361208_p92078mnxbtremattroilucnuadembia1.jpg");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeyWord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MonthScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasDefaultValue("Product");

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("Sale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("WeekScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("YearScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("isDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Eren Yeager",
                            Available = 0,
                            CategoryId = 1,
                            Description = @"Nhà xuất bản Trẻ giới thiệu đến Quý vị tập sách mới trong bộ sách Chạng vạng của tác giả Stephanie Mayer là Mặt trời lúc nửa đêm. Bộ tiểu thuyết Chạng vạng gồm 4 tập là Chạng vạng, Trăng non, Nhật thực, Hừng đông đã thu hút hàng triệu độc giả trên toàn thế giới, trở thành tác phẩm kinh điển định hình lại dòng văn học dành cho bạn đọc trẻ và dấy lên một hiện tượng lạ khiến độc giả khao khát chờ đợi phần tiếp theo. Loạt truyện đã bán được 160 triệu bản ở nhiều quốc gia và dựng thành năm bộ phim bom tấn. Ở Việt Nam, bộ sách cũng đã tạo nên cơn sốt ngay khi phát hành và liên tục bán chạy qua nhiều năm.

Mặt trời lúc nửa đêm (tựa gốc: Midnight Sun), tập sách mới nhất trong bộ Chạng vạng, cũng đã nối tiếp thành công của các tựa sách trước đó. Chỉ trong tuần đầu phát hành, cuốn sách đã bán ngay được 1 triệu bản ở thị trường Âu – Mỹ.

Khi Edward Cullen và Bella Swan gặp nhau trong Chạng vạng, một chuyện tình yêu mang tính biểu tượng đã ra đời. Nhưng cho đến bây giờ, người hâm mộ chỉ nghe thấy câu chuyện từ góc nhìn của Bella. Cuối cùng, độc giả đã có thể trải nghiệm phiên bản của Edward trong cuốn tiểu thuyết đồng hành đã được chờ đợi từ lâu, Mặt trời lúc nửa đêm.

Câu chuyện đen tối này được kể qua đôi mắt của Edward với nhiều mới mẻ và những bước ngoặt quyết định. Gặp gỡ Bella vừa là sự kiện hấp dẫn nhất, cũng là điều đáng sợ nhất mà anh đã trải qua trong suốt những năm tháng làm ma cà rồng. Khi tìm hiểu thêm các chi tiết lạ lùng trong quá khứ Edward cũng như nội tâm phức tạp của anh, chúng ta sẽ hiểu tại sao đây là cuộc chiến quyết định trong đời Edward. Anh sẽ biện minh cho trái tim mình thế nào nếu yêu Bella cũng đồng nghĩa với việc dẫn cô đến với nguy hiểm?

Trong Mặt trời lúc nửa đêm, Stephenie Meyer đưa chúng ta trở lại một thế giới đã thu hút hàng triệu độc giả, và mang đến một tiểu thuyết gay cấn về niềm vui và hậu quả tàn khốc của tình yêu bất tử.

Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Tuy nhiên tuỳ vào từng loại sản phẩm hoặc phương thức, địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, ...",
                            KeyWord = "SachHay, SachRe",
                            MonthScore = 0,
                            Name = "Mặt Trời Lúc Nửa Đêm",
                            Price = 10000m,
                            Sale = 0m,
                            WeekScore = 10,
                            YearScore = 0,
                            isDelete = false
                        },
                        new
                        {
                            Id = 2,
                            Author = "Eren Yeager",
                            Available = 0,
                            CategoryId = 1,
                            Description = @"Nhà xuất bản Trẻ giới thiệu đến Quý vị tập sách mới trong bộ sách Chạng vạng của tác giả Stephanie Mayer là Mặt trời lúc nửa đêm. Bộ tiểu thuyết Chạng vạng gồm 4 tập là Chạng vạng, Trăng non, Nhật thực, Hừng đông đã thu hút hàng triệu độc giả trên toàn thế giới, trở thành tác phẩm kinh điển định hình lại dòng văn học dành cho bạn đọc trẻ và dấy lên một hiện tượng lạ khiến độc giả khao khát chờ đợi phần tiếp theo. Loạt truyện đã bán được 160 triệu bản ở nhiều quốc gia và dựng thành năm bộ phim bom tấn. Ở Việt Nam, bộ sách cũng đã tạo nên cơn sốt ngay khi phát hành và liên tục bán chạy qua nhiều năm.

Mặt trời lúc nửa đêm (tựa gốc: Midnight Sun), tập sách mới nhất trong bộ Chạng vạng, cũng đã nối tiếp thành công của các tựa sách trước đó. Chỉ trong tuần đầu phát hành, cuốn sách đã bán ngay được 1 triệu bản ở thị trường Âu – Mỹ.

Khi Edward Cullen và Bella Swan gặp nhau trong Chạng vạng, một chuyện tình yêu mang tính biểu tượng đã ra đời. Nhưng cho đến bây giờ, người hâm mộ chỉ nghe thấy câu chuyện từ góc nhìn của Bella. Cuối cùng, độc giả đã có thể trải nghiệm phiên bản của Edward trong cuốn tiểu thuyết đồng hành đã được chờ đợi từ lâu, Mặt trời lúc nửa đêm.

Câu chuyện đen tối này được kể qua đôi mắt của Edward với nhiều mới mẻ và những bước ngoặt quyết định. Gặp gỡ Bella vừa là sự kiện hấp dẫn nhất, cũng là điều đáng sợ nhất mà anh đã trải qua trong suốt những năm tháng làm ma cà rồng. Khi tìm hiểu thêm các chi tiết lạ lùng trong quá khứ Edward cũng như nội tâm phức tạp của anh, chúng ta sẽ hiểu tại sao đây là cuộc chiến quyết định trong đời Edward. Anh sẽ biện minh cho trái tim mình thế nào nếu yêu Bella cũng đồng nghĩa với việc dẫn cô đến với nguy hiểm?

Trong Mặt trời lúc nửa đêm, Stephenie Meyer đưa chúng ta trở lại một thế giới đã thu hút hàng triệu độc giả, và mang đến một tiểu thuyết gay cấn về niềm vui và hậu quả tàn khốc của tình yêu bất tử.

Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Tuy nhiên tuỳ vào từng loại sản phẩm hoặc phương thức, địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, ...",
                            KeyWord = "SachHay, SachRe",
                            MonthScore = 10,
                            Name = "Mặt Trời Lúc Nửa Đêm",
                            Price = 10000m,
                            Sale = 0m,
                            WeekScore = 0,
                            YearScore = 0,
                            isDelete = false
                        },
                        new
                        {
                            Id = 3,
                            Author = "Eren Yeager",
                            Available = 10,
                            CategoryId = 1,
                            Description = @"Nhà xuất bản Trẻ giới thiệu đến Quý vị tập sách mới trong bộ sách Chạng vạng của tác giả Stephanie Mayer là Mặt trời lúc nửa đêm. Bộ tiểu thuyết Chạng vạng gồm 4 tập là Chạng vạng, Trăng non, Nhật thực, Hừng đông đã thu hút hàng triệu độc giả trên toàn thế giới, trở thành tác phẩm kinh điển định hình lại dòng văn học dành cho bạn đọc trẻ và dấy lên một hiện tượng lạ khiến độc giả khao khát chờ đợi phần tiếp theo. Loạt truyện đã bán được 160 triệu bản ở nhiều quốc gia và dựng thành năm bộ phim bom tấn. Ở Việt Nam, bộ sách cũng đã tạo nên cơn sốt ngay khi phát hành và liên tục bán chạy qua nhiều năm.

Mặt trời lúc nửa đêm (tựa gốc: Midnight Sun), tập sách mới nhất trong bộ Chạng vạng, cũng đã nối tiếp thành công của các tựa sách trước đó. Chỉ trong tuần đầu phát hành, cuốn sách đã bán ngay được 1 triệu bản ở thị trường Âu – Mỹ.

Khi Edward Cullen và Bella Swan gặp nhau trong Chạng vạng, một chuyện tình yêu mang tính biểu tượng đã ra đời. Nhưng cho đến bây giờ, người hâm mộ chỉ nghe thấy câu chuyện từ góc nhìn của Bella. Cuối cùng, độc giả đã có thể trải nghiệm phiên bản của Edward trong cuốn tiểu thuyết đồng hành đã được chờ đợi từ lâu, Mặt trời lúc nửa đêm.

Câu chuyện đen tối này được kể qua đôi mắt của Edward với nhiều mới mẻ và những bước ngoặt quyết định. Gặp gỡ Bella vừa là sự kiện hấp dẫn nhất, cũng là điều đáng sợ nhất mà anh đã trải qua trong suốt những năm tháng làm ma cà rồng. Khi tìm hiểu thêm các chi tiết lạ lùng trong quá khứ Edward cũng như nội tâm phức tạp của anh, chúng ta sẽ hiểu tại sao đây là cuộc chiến quyết định trong đời Edward. Anh sẽ biện minh cho trái tim mình thế nào nếu yêu Bella cũng đồng nghĩa với việc dẫn cô đến với nguy hiểm?

Trong Mặt trời lúc nửa đêm, Stephenie Meyer đưa chúng ta trở lại một thế giới đã thu hút hàng triệu độc giả, và mang đến một tiểu thuyết gay cấn về niềm vui và hậu quả tàn khốc của tình yêu bất tử.

Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Tuy nhiên tuỳ vào từng loại sản phẩm hoặc phương thức, địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, ...",
                            KeyWord = "SachHay, SachRe",
                            MonthScore = 0,
                            Name = "Mặt Trời Lúc Nửa Đêm",
                            Price = 10000m,
                            Sale = 0m,
                            WeekScore = 0,
                            YearScore = 10,
                            isDelete = false
                        },
                        new
                        {
                            Id = 4,
                            Author = "Eren Yeager",
                            Available = 10,
                            CategoryId = 1,
                            Description = @"Nhà xuất bản Trẻ giới thiệu đến Quý vị tập sách mới trong bộ sách Chạng vạng của tác giả Stephanie Mayer là Mặt trời lúc nửa đêm. Bộ tiểu thuyết Chạng vạng gồm 4 tập là Chạng vạng, Trăng non, Nhật thực, Hừng đông đã thu hút hàng triệu độc giả trên toàn thế giới, trở thành tác phẩm kinh điển định hình lại dòng văn học dành cho bạn đọc trẻ và dấy lên một hiện tượng lạ khiến độc giả khao khát chờ đợi phần tiếp theo. Loạt truyện đã bán được 160 triệu bản ở nhiều quốc gia và dựng thành năm bộ phim bom tấn. Ở Việt Nam, bộ sách cũng đã tạo nên cơn sốt ngay khi phát hành và liên tục bán chạy qua nhiều năm.

Mặt trời lúc nửa đêm (tựa gốc: Midnight Sun), tập sách mới nhất trong bộ Chạng vạng, cũng đã nối tiếp thành công của các tựa sách trước đó. Chỉ trong tuần đầu phát hành, cuốn sách đã bán ngay được 1 triệu bản ở thị trường Âu – Mỹ.

Khi Edward Cullen và Bella Swan gặp nhau trong Chạng vạng, một chuyện tình yêu mang tính biểu tượng đã ra đời. Nhưng cho đến bây giờ, người hâm mộ chỉ nghe thấy câu chuyện từ góc nhìn của Bella. Cuối cùng, độc giả đã có thể trải nghiệm phiên bản của Edward trong cuốn tiểu thuyết đồng hành đã được chờ đợi từ lâu, Mặt trời lúc nửa đêm.

Câu chuyện đen tối này được kể qua đôi mắt của Edward với nhiều mới mẻ và những bước ngoặt quyết định. Gặp gỡ Bella vừa là sự kiện hấp dẫn nhất, cũng là điều đáng sợ nhất mà anh đã trải qua trong suốt những năm tháng làm ma cà rồng. Khi tìm hiểu thêm các chi tiết lạ lùng trong quá khứ Edward cũng như nội tâm phức tạp của anh, chúng ta sẽ hiểu tại sao đây là cuộc chiến quyết định trong đời Edward. Anh sẽ biện minh cho trái tim mình thế nào nếu yêu Bella cũng đồng nghĩa với việc dẫn cô đến với nguy hiểm?

Trong Mặt trời lúc nửa đêm, Stephenie Meyer đưa chúng ta trở lại một thế giới đã thu hút hàng triệu độc giả, và mang đến một tiểu thuyết gay cấn về niềm vui và hậu quả tàn khốc của tình yêu bất tử.

Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Tuy nhiên tuỳ vào từng loại sản phẩm hoặc phương thức, địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, ...",
                            KeyWord = "SachHay, SachRe",
                            MonthScore = 0,
                            Name = "Mặt Trời Lúc Nửa Đêm",
                            Price = 10000m,
                            Sale = 0m,
                            WeekScore = 0,
                            YearScore = 0,
                            isDelete = false
                        },
                        new
                        {
                            Id = 5,
                            Author = "Eren Yeager",
                            Available = 10,
                            CategoryId = 1,
                            Description = @"Nhà xuất bản Trẻ giới thiệu đến Quý vị tập sách mới trong bộ sách Chạng vạng của tác giả Stephanie Mayer là Mặt trời lúc nửa đêm. Bộ tiểu thuyết Chạng vạng gồm 4 tập là Chạng vạng, Trăng non, Nhật thực, Hừng đông đã thu hút hàng triệu độc giả trên toàn thế giới, trở thành tác phẩm kinh điển định hình lại dòng văn học dành cho bạn đọc trẻ và dấy lên một hiện tượng lạ khiến độc giả khao khát chờ đợi phần tiếp theo. Loạt truyện đã bán được 160 triệu bản ở nhiều quốc gia và dựng thành năm bộ phim bom tấn. Ở Việt Nam, bộ sách cũng đã tạo nên cơn sốt ngay khi phát hành và liên tục bán chạy qua nhiều năm.

Mặt trời lúc nửa đêm (tựa gốc: Midnight Sun), tập sách mới nhất trong bộ Chạng vạng, cũng đã nối tiếp thành công của các tựa sách trước đó. Chỉ trong tuần đầu phát hành, cuốn sách đã bán ngay được 1 triệu bản ở thị trường Âu – Mỹ.

Khi Edward Cullen và Bella Swan gặp nhau trong Chạng vạng, một chuyện tình yêu mang tính biểu tượng đã ra đời. Nhưng cho đến bây giờ, người hâm mộ chỉ nghe thấy câu chuyện từ góc nhìn của Bella. Cuối cùng, độc giả đã có thể trải nghiệm phiên bản của Edward trong cuốn tiểu thuyết đồng hành đã được chờ đợi từ lâu, Mặt trời lúc nửa đêm.

Câu chuyện đen tối này được kể qua đôi mắt của Edward với nhiều mới mẻ và những bước ngoặt quyết định. Gặp gỡ Bella vừa là sự kiện hấp dẫn nhất, cũng là điều đáng sợ nhất mà anh đã trải qua trong suốt những năm tháng làm ma cà rồng. Khi tìm hiểu thêm các chi tiết lạ lùng trong quá khứ Edward cũng như nội tâm phức tạp của anh, chúng ta sẽ hiểu tại sao đây là cuộc chiến quyết định trong đời Edward. Anh sẽ biện minh cho trái tim mình thế nào nếu yêu Bella cũng đồng nghĩa với việc dẫn cô đến với nguy hiểm?

Trong Mặt trời lúc nửa đêm, Stephenie Meyer đưa chúng ta trở lại một thế giới đã thu hút hàng triệu độc giả, và mang đến một tiểu thuyết gay cấn về niềm vui và hậu quả tàn khốc của tình yêu bất tử.

Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Tuy nhiên tuỳ vào từng loại sản phẩm hoặc phương thức, địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, ...",
                            KeyWord = "SachHay, SachRe",
                            MonthScore = 0,
                            Name = "Mặt Trời Lúc Nửa Đêm",
                            Price = 10000m,
                            Sale = 0m,
                            WeekScore = 0,
                            YearScore = 0,
                            isDelete = false
                        },
                        new
                        {
                            Id = 6,
                            Author = "Eren Yeager",
                            Available = 10,
                            CategoryId = 1,
                            Description = @"Nhà xuất bản Trẻ giới thiệu đến Quý vị tập sách mới trong bộ sách Chạng vạng của tác giả Stephanie Mayer là Mặt trời lúc nửa đêm. Bộ tiểu thuyết Chạng vạng gồm 4 tập là Chạng vạng, Trăng non, Nhật thực, Hừng đông đã thu hút hàng triệu độc giả trên toàn thế giới, trở thành tác phẩm kinh điển định hình lại dòng văn học dành cho bạn đọc trẻ và dấy lên một hiện tượng lạ khiến độc giả khao khát chờ đợi phần tiếp theo. Loạt truyện đã bán được 160 triệu bản ở nhiều quốc gia và dựng thành năm bộ phim bom tấn. Ở Việt Nam, bộ sách cũng đã tạo nên cơn sốt ngay khi phát hành và liên tục bán chạy qua nhiều năm.

Mặt trời lúc nửa đêm (tựa gốc: Midnight Sun), tập sách mới nhất trong bộ Chạng vạng, cũng đã nối tiếp thành công của các tựa sách trước đó. Chỉ trong tuần đầu phát hành, cuốn sách đã bán ngay được 1 triệu bản ở thị trường Âu – Mỹ.

Khi Edward Cullen và Bella Swan gặp nhau trong Chạng vạng, một chuyện tình yêu mang tính biểu tượng đã ra đời. Nhưng cho đến bây giờ, người hâm mộ chỉ nghe thấy câu chuyện từ góc nhìn của Bella. Cuối cùng, độc giả đã có thể trải nghiệm phiên bản của Edward trong cuốn tiểu thuyết đồng hành đã được chờ đợi từ lâu, Mặt trời lúc nửa đêm.

Câu chuyện đen tối này được kể qua đôi mắt của Edward với nhiều mới mẻ và những bước ngoặt quyết định. Gặp gỡ Bella vừa là sự kiện hấp dẫn nhất, cũng là điều đáng sợ nhất mà anh đã trải qua trong suốt những năm tháng làm ma cà rồng. Khi tìm hiểu thêm các chi tiết lạ lùng trong quá khứ Edward cũng như nội tâm phức tạp của anh, chúng ta sẽ hiểu tại sao đây là cuộc chiến quyết định trong đời Edward. Anh sẽ biện minh cho trái tim mình thế nào nếu yêu Bella cũng đồng nghĩa với việc dẫn cô đến với nguy hiểm?

Trong Mặt trời lúc nửa đêm, Stephenie Meyer đưa chúng ta trở lại một thế giới đã thu hút hàng triệu độc giả, và mang đến một tiểu thuyết gay cấn về niềm vui và hậu quả tàn khốc của tình yêu bất tử.

Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Tuy nhiên tuỳ vào từng loại sản phẩm hoặc phương thức, địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, ...",
                            KeyWord = "SachHay, SachRe",
                            MonthScore = 0,
                            Name = "Mặt Trời Lúc Nửa Đêm",
                            Price = 10000m,
                            Sale = 0m,
                            WeekScore = 0,
                            YearScore = 0,
                            isDelete = false
                        },
                        new
                        {
                            Id = 7,
                            Author = "Eren Yeager",
                            Available = 10,
                            CategoryId = 1,
                            Description = @"Nhà xuất bản Trẻ giới thiệu đến Quý vị tập sách mới trong bộ sách Chạng vạng của tác giả Stephanie Mayer là Mặt trời lúc nửa đêm. Bộ tiểu thuyết Chạng vạng gồm 4 tập là Chạng vạng, Trăng non, Nhật thực, Hừng đông đã thu hút hàng triệu độc giả trên toàn thế giới, trở thành tác phẩm kinh điển định hình lại dòng văn học dành cho bạn đọc trẻ và dấy lên một hiện tượng lạ khiến độc giả khao khát chờ đợi phần tiếp theo. Loạt truyện đã bán được 160 triệu bản ở nhiều quốc gia và dựng thành năm bộ phim bom tấn. Ở Việt Nam, bộ sách cũng đã tạo nên cơn sốt ngay khi phát hành và liên tục bán chạy qua nhiều năm.

Mặt trời lúc nửa đêm (tựa gốc: Midnight Sun), tập sách mới nhất trong bộ Chạng vạng, cũng đã nối tiếp thành công của các tựa sách trước đó. Chỉ trong tuần đầu phát hành, cuốn sách đã bán ngay được 1 triệu bản ở thị trường Âu – Mỹ.

Khi Edward Cullen và Bella Swan gặp nhau trong Chạng vạng, một chuyện tình yêu mang tính biểu tượng đã ra đời. Nhưng cho đến bây giờ, người hâm mộ chỉ nghe thấy câu chuyện từ góc nhìn của Bella. Cuối cùng, độc giả đã có thể trải nghiệm phiên bản của Edward trong cuốn tiểu thuyết đồng hành đã được chờ đợi từ lâu, Mặt trời lúc nửa đêm.

Câu chuyện đen tối này được kể qua đôi mắt của Edward với nhiều mới mẻ và những bước ngoặt quyết định. Gặp gỡ Bella vừa là sự kiện hấp dẫn nhất, cũng là điều đáng sợ nhất mà anh đã trải qua trong suốt những năm tháng làm ma cà rồng. Khi tìm hiểu thêm các chi tiết lạ lùng trong quá khứ Edward cũng như nội tâm phức tạp của anh, chúng ta sẽ hiểu tại sao đây là cuộc chiến quyết định trong đời Edward. Anh sẽ biện minh cho trái tim mình thế nào nếu yêu Bella cũng đồng nghĩa với việc dẫn cô đến với nguy hiểm?

Trong Mặt trời lúc nửa đêm, Stephenie Meyer đưa chúng ta trở lại một thế giới đã thu hút hàng triệu độc giả, và mang đến một tiểu thuyết gay cấn về niềm vui và hậu quả tàn khốc của tình yêu bất tử.

Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Tuy nhiên tuỳ vào từng loại sản phẩm hoặc phương thức, địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, ...",
                            MonthScore = 0,
                            Name = "Mặt Trời Lúc Nửa Đêm",
                            Price = 10000m,
                            Sale = 0m,
                            WeekScore = 0,
                            YearScore = 0,
                            isDelete = false
                        },
                        new
                        {
                            Id = 8,
                            Author = "Eren Yeager",
                            Available = 10,
                            CategoryId = 1,
                            Description = @"Nhà xuất bản Trẻ giới thiệu đến Quý vị tập sách mới trong bộ sách Chạng vạng của tác giả Stephanie Mayer là Mặt trời lúc nửa đêm. Bộ tiểu thuyết Chạng vạng gồm 4 tập là Chạng vạng, Trăng non, Nhật thực, Hừng đông đã thu hút hàng triệu độc giả trên toàn thế giới, trở thành tác phẩm kinh điển định hình lại dòng văn học dành cho bạn đọc trẻ và dấy lên một hiện tượng lạ khiến độc giả khao khát chờ đợi phần tiếp theo. Loạt truyện đã bán được 160 triệu bản ở nhiều quốc gia và dựng thành năm bộ phim bom tấn. Ở Việt Nam, bộ sách cũng đã tạo nên cơn sốt ngay khi phát hành và liên tục bán chạy qua nhiều năm.

Mặt trời lúc nửa đêm (tựa gốc: Midnight Sun), tập sách mới nhất trong bộ Chạng vạng, cũng đã nối tiếp thành công của các tựa sách trước đó. Chỉ trong tuần đầu phát hành, cuốn sách đã bán ngay được 1 triệu bản ở thị trường Âu – Mỹ.

Khi Edward Cullen và Bella Swan gặp nhau trong Chạng vạng, một chuyện tình yêu mang tính biểu tượng đã ra đời. Nhưng cho đến bây giờ, người hâm mộ chỉ nghe thấy câu chuyện từ góc nhìn của Bella. Cuối cùng, độc giả đã có thể trải nghiệm phiên bản của Edward trong cuốn tiểu thuyết đồng hành đã được chờ đợi từ lâu, Mặt trời lúc nửa đêm.

Câu chuyện đen tối này được kể qua đôi mắt của Edward với nhiều mới mẻ và những bước ngoặt quyết định. Gặp gỡ Bella vừa là sự kiện hấp dẫn nhất, cũng là điều đáng sợ nhất mà anh đã trải qua trong suốt những năm tháng làm ma cà rồng. Khi tìm hiểu thêm các chi tiết lạ lùng trong quá khứ Edward cũng như nội tâm phức tạp của anh, chúng ta sẽ hiểu tại sao đây là cuộc chiến quyết định trong đời Edward. Anh sẽ biện minh cho trái tim mình thế nào nếu yêu Bella cũng đồng nghĩa với việc dẫn cô đến với nguy hiểm?

Trong Mặt trời lúc nửa đêm, Stephenie Meyer đưa chúng ta trở lại một thế giới đã thu hút hàng triệu độc giả, và mang đến một tiểu thuyết gay cấn về niềm vui và hậu quả tàn khốc của tình yêu bất tử.

Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Tuy nhiên tuỳ vào từng loại sản phẩm hoặc phương thức, địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, ...",
                            MonthScore = 0,
                            Name = "Mặt Trời Lúc Nửa Đêm",
                            Price = 10000m,
                            Sale = 0m,
                            WeekScore = 0,
                            YearScore = 0,
                            isDelete = false
                        },
                        new
                        {
                            Id = 9,
                            Author = "Eren Yeager",
                            Available = 10,
                            CategoryId = 1,
                            Description = @"Nhà xuất bản Trẻ giới thiệu đến Quý vị tập sách mới trong bộ sách Chạng vạng của tác giả Stephanie Mayer là Mặt trời lúc nửa đêm. Bộ tiểu thuyết Chạng vạng gồm 4 tập là Chạng vạng, Trăng non, Nhật thực, Hừng đông đã thu hút hàng triệu độc giả trên toàn thế giới, trở thành tác phẩm kinh điển định hình lại dòng văn học dành cho bạn đọc trẻ và dấy lên một hiện tượng lạ khiến độc giả khao khát chờ đợi phần tiếp theo. Loạt truyện đã bán được 160 triệu bản ở nhiều quốc gia và dựng thành năm bộ phim bom tấn. Ở Việt Nam, bộ sách cũng đã tạo nên cơn sốt ngay khi phát hành và liên tục bán chạy qua nhiều năm.

Mặt trời lúc nửa đêm (tựa gốc: Midnight Sun), tập sách mới nhất trong bộ Chạng vạng, cũng đã nối tiếp thành công của các tựa sách trước đó. Chỉ trong tuần đầu phát hành, cuốn sách đã bán ngay được 1 triệu bản ở thị trường Âu – Mỹ.

Khi Edward Cullen và Bella Swan gặp nhau trong Chạng vạng, một chuyện tình yêu mang tính biểu tượng đã ra đời. Nhưng cho đến bây giờ, người hâm mộ chỉ nghe thấy câu chuyện từ góc nhìn của Bella. Cuối cùng, độc giả đã có thể trải nghiệm phiên bản của Edward trong cuốn tiểu thuyết đồng hành đã được chờ đợi từ lâu, Mặt trời lúc nửa đêm.

Câu chuyện đen tối này được kể qua đôi mắt của Edward với nhiều mới mẻ và những bước ngoặt quyết định. Gặp gỡ Bella vừa là sự kiện hấp dẫn nhất, cũng là điều đáng sợ nhất mà anh đã trải qua trong suốt những năm tháng làm ma cà rồng. Khi tìm hiểu thêm các chi tiết lạ lùng trong quá khứ Edward cũng như nội tâm phức tạp của anh, chúng ta sẽ hiểu tại sao đây là cuộc chiến quyết định trong đời Edward. Anh sẽ biện minh cho trái tim mình thế nào nếu yêu Bella cũng đồng nghĩa với việc dẫn cô đến với nguy hiểm?

Trong Mặt trời lúc nửa đêm, Stephenie Meyer đưa chúng ta trở lại một thế giới đã thu hút hàng triệu độc giả, và mang đến một tiểu thuyết gay cấn về niềm vui và hậu quả tàn khốc của tình yêu bất tử.

Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Tuy nhiên tuỳ vào từng loại sản phẩm hoặc phương thức, địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, ...",
                            MonthScore = 0,
                            Name = "Mặt Trời Lúc Nửa Đêm",
                            Price = 10000m,
                            Sale = 0m,
                            WeekScore = 0,
                            YearScore = 0,
                            isDelete = false
                        },
                        new
                        {
                            Id = 10,
                            Author = "Eren Yeager",
                            Available = 10,
                            CategoryId = 1,
                            Description = @"Nhà xuất bản Trẻ giới thiệu đến Quý vị tập sách mới trong bộ sách Chạng vạng của tác giả Stephanie Mayer là Mặt trời lúc nửa đêm. Bộ tiểu thuyết Chạng vạng gồm 4 tập là Chạng vạng, Trăng non, Nhật thực, Hừng đông đã thu hút hàng triệu độc giả trên toàn thế giới, trở thành tác phẩm kinh điển định hình lại dòng văn học dành cho bạn đọc trẻ và dấy lên một hiện tượng lạ khiến độc giả khao khát chờ đợi phần tiếp theo. Loạt truyện đã bán được 160 triệu bản ở nhiều quốc gia và dựng thành năm bộ phim bom tấn. Ở Việt Nam, bộ sách cũng đã tạo nên cơn sốt ngay khi phát hành và liên tục bán chạy qua nhiều năm.

Mặt trời lúc nửa đêm (tựa gốc: Midnight Sun), tập sách mới nhất trong bộ Chạng vạng, cũng đã nối tiếp thành công của các tựa sách trước đó. Chỉ trong tuần đầu phát hành, cuốn sách đã bán ngay được 1 triệu bản ở thị trường Âu – Mỹ.

Khi Edward Cullen và Bella Swan gặp nhau trong Chạng vạng, một chuyện tình yêu mang tính biểu tượng đã ra đời. Nhưng cho đến bây giờ, người hâm mộ chỉ nghe thấy câu chuyện từ góc nhìn của Bella. Cuối cùng, độc giả đã có thể trải nghiệm phiên bản của Edward trong cuốn tiểu thuyết đồng hành đã được chờ đợi từ lâu, Mặt trời lúc nửa đêm.

Câu chuyện đen tối này được kể qua đôi mắt của Edward với nhiều mới mẻ và những bước ngoặt quyết định. Gặp gỡ Bella vừa là sự kiện hấp dẫn nhất, cũng là điều đáng sợ nhất mà anh đã trải qua trong suốt những năm tháng làm ma cà rồng. Khi tìm hiểu thêm các chi tiết lạ lùng trong quá khứ Edward cũng như nội tâm phức tạp của anh, chúng ta sẽ hiểu tại sao đây là cuộc chiến quyết định trong đời Edward. Anh sẽ biện minh cho trái tim mình thế nào nếu yêu Bella cũng đồng nghĩa với việc dẫn cô đến với nguy hiểm?

Trong Mặt trời lúc nửa đêm, Stephenie Meyer đưa chúng ta trở lại một thế giới đã thu hút hàng triệu độc giả, và mang đến một tiểu thuyết gay cấn về niềm vui và hậu quả tàn khốc của tình yêu bất tử.

Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Tuy nhiên tuỳ vào từng loại sản phẩm hoặc phương thức, địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, ...",
                            MonthScore = 0,
                            Name = "Mặt Trời Lúc Nửa Đêm",
                            Price = 10000m,
                            Sale = 0m,
                            WeekScore = 0,
                            YearScore = 0,
                            isDelete = false
                        });
                });

            modelBuilder.Entity("DataLayer.Entities.BookRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("BookRatings");
                });

            modelBuilder.Entity("DataLayer.Entities.CartItem", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("UserId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("DataLayer.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KeyWord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KeyWord = "vanhoc, van hoc",
                            Name = "Văn học"
                        },
                        new
                        {
                            Id = 2,
                            KeyWord = "kinhte, kinh te",
                            Name = "Kinh tế"
                        },
                        new
                        {
                            Id = 3,
                            KeyWord = "thieunhi, thieu nhi",
                            Name = "Thiếu nhi"
                        },
                        new
                        {
                            Id = 4,
                            KeyWord = "ngoaingu, ngoai ngu",
                            Name = "Ngoại ngữ"
                        },
                        new
                        {
                            Id = 5,
                            KeyWord = "khoa hoc ki thuat, khoa hoc ky thuat, Khoa học kỹ thuật",
                            Name = "Khoa học kĩ thuật"
                        },
                        new
                        {
                            Id = 6,
                            KeyWord = "lich su, dia li, dia ly, ton giao",
                            Name = "Lịch sử - Địa lý - Tôn giáo"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Khác"
                        });
                });

            modelBuilder.Entity("DataLayer.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime>("DateCreate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2020, 12, 22, 21, 8, 43, 157, DateTimeKind.Local).AddTicks(6748));

                    b.Property<DateTime?>("DateModify")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateReceive")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateReturn")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DataLayer.Entities.OrderDetail", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal>("TotalPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("OrderId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("DataLayer.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7d2e5394-ddc3-4bbc-9ecb-327f2f37ce6c"),
                            ConcurrencyStamp = "3f371af9-ae54-494d-b1a5-5ee3154e1395",
                            Name = "Administrator",
                            NormalizedName = "Administrator"
                        },
                        new
                        {
                            Id = new Guid("61e1c8dc-a9ae-411e-98d9-110ae7afe2cb"),
                            ConcurrencyStamp = "e2156f0a-672f-4236-845a-8eb6e4057839",
                            Name = "Sales",
                            NormalizedName = "Sales"
                        },
                        new
                        {
                            Id = new Guid("d5388079-d681-444e-8291-99cdf0c71973"),
                            ConcurrencyStamp = "cb3458d3-4f09-457a-9dd5-16844d0e7596",
                            Name = "User",
                            NormalizedName = "User"
                        });
                });

            modelBuilder.Entity("DataLayer.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200)
                        .HasDefaultValue("none");

                    b.Property<string>("Avatar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("https://www.pavilionweb.com/wp-content/uploads/2017/03/man-300x300.png");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(true);

                    b.Property<bool>("IsMale")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("isUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("de8781ce-01a8-1ac1-88ad-99ef6caf6957"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "339fcdce-e3b0-4dcb-8d15-dc94ca600b62",
                            Dob = new DateTime(2020, 12, 22, 21, 8, 43, 187, DateTimeKind.Local).AddTicks(7970),
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Administrator",
                            IsMale = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "admin@gmail.com",
                            NormalizedUserName = "admin",
                            PasswordHash = "AQAAAAEAACcQAAAAEGsvIH5nQEJP+zli8NbLlNjPn5MJdJWuNt0lCNk2BIUqFJ/nwxzCEY+QEkzOLg+4+A==",
                            PhoneNumber = "0123456788",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin",
                            isDelete = false,
                            isUser = false
                        },
                        new
                        {
                            Id = new Guid("defaac82-a5df-4f59-8b28-f2674cb44f05"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ff96f297-18c9-45e9-a4b9-e5c0d0d83fba",
                            Dob = new DateTime(2020, 12, 22, 21, 8, 43, 197, DateTimeKind.Local).AddTicks(4441),
                            Email = "sales@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Sales 1",
                            IsMale = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "sales@gmail.com",
                            NormalizedUserName = "sales",
                            PasswordHash = "AQAAAAEAACcQAAAAEO2mM62PeZKYlAunOiZGUrudh8Gz5GjLaHFyKK33rXV0fjo7eaDTNpMBxkKZIj0QMQ==",
                            PhoneNumber = "0123456789",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "sales",
                            isDelete = false,
                            isUser = false
                        },
                        new
                        {
                            Id = new Guid("5e814bd0-7504-4e1f-8dba-fdf01031cae6"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "19a21dbd-4373-4222-b524-edcb378813aa",
                            Dob = new DateTime(2020, 12, 22, 21, 8, 43, 206, DateTimeKind.Local).AddTicks(965),
                            Email = "user@gmail.com",
                            EmailConfirmed = true,
                            FullName = "User 1",
                            IsMale = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "user@gmail.com",
                            NormalizedUserName = "user",
                            PasswordHash = "AQAAAAEAACcQAAAAENyGYwCYv4VMAv78N5ZD+PJAnEJhVrQpEzEWyi3AZ7pscQZ2VvdZt33YGrSv5CM/8A==",
                            PhoneNumber = "0123456787",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "user",
                            isDelete = false,
                            isUser = true
                        });
                });

            modelBuilder.Entity("DataLayer.Entities.UserRole", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("7d2e5394-ddc3-4bbc-9ecb-327f2f37ce6c"),
                            UserId = new Guid("de8781ce-01a8-1ac1-88ad-99ef6caf6957")
                        },
                        new
                        {
                            RoleId = new Guid("61e1c8dc-a9ae-411e-98d9-110ae7afe2cb"),
                            UserId = new Guid("defaac82-a5df-4f59-8b28-f2674cb44f05")
                        },
                        new
                        {
                            RoleId = new Guid("d5388079-d681-444e-8291-99cdf0c71973"),
                            UserId = new Guid("5e814bd0-7504-4e1f-8dba-fdf01031cae6")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("DataLayer.Entities.Blog", b =>
                {
                    b.HasOne("DataLayer.Entities.User", "User")
                        .WithMany("Blogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataLayer.Entities.Book", b =>
                {
                    b.HasOne("DataLayer.Entities.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataLayer.Entities.BookRating", b =>
                {
                    b.HasOne("DataLayer.Entities.Book", "Book")
                        .WithMany("BookRatings")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Entities.User", "User")
                        .WithMany("BookRatings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataLayer.Entities.CartItem", b =>
                {
                    b.HasOne("DataLayer.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Entities.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataLayer.Entities.Order", b =>
                {
                    b.HasOne("DataLayer.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataLayer.Entities.OrderDetail", b =>
                {
                    b.HasOne("DataLayer.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataLayer.Entities.UserRole", b =>
                {
                    b.HasOne("DataLayer.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
